local proto = require("rtlbuddy.protocol")

describe("rtlbuddy.protocol", function()
  it("encode then decode round-trips a hello", function()
    local env = proto.hello("0.1.0", { "open_source" })
    local line = proto.encode(env)
    local back = proto.decode(line)
    assert.are.equal(env.id, back.id)
    assert.are.equal("hello", back.type)
    assert.are.equal("request", back.kind)
    assert.are.equal("src", back.origin)
    assert.are.equal(1, back.v)
    assert.are.equal("src", back.payload.client)
  end)

  it("source_focused carries file/line/col", function()
    local env = proto.source_focused("/abs/path.sv", 12, 3)
    assert.are.equal("event", env.kind)
    assert.are.equal("source_focused", env.type)
    assert.are.equal(12, env.payload.line)
    assert.are.equal(3, env.payload.col)
  end)

  it("rejects malformed wire frames", function()
    assert.has_error(function()
      proto.decode("")
    end)
    assert.has_error(function()
      proto.decode("not json")
    end)
    assert.has_error(function()
      proto.decode(vim.json.encode({ v = 2, id = "x", origin = "src", kind = "event", type = "x" }))
    end)
    assert.has_error(function()
      proto.decode(
        vim.json.encode({ v = 1, id = "x", origin = "nope", kind = "event", type = "x" })
      )
    end)
  end)

  it("new_id produces RFC-4122 v4-shaped strings", function()
    local id = proto.new_id()
    assert.is_true(id:match("^[0-9a-f]+-[0-9a-f]+-4[0-9a-f]+-[89ab][0-9a-f]+-[0-9a-f]+$") ~= nil)
  end)
end)
